version: 2
updates:
  - package-ecosystem: 'pub'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Asia/Tokyo'

  - package-ecosystem: 'gradle'
    directory: '/android'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Asia/Tokyo'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Asia/Tokyo'
