name: TokoBus
description: 早稲田大学所沢キャンパスのスクールバス時刻表アプリです。
publish_to: 'none'

version: 2.9.4+142

environment:
  sdk: ^3.6.0  # ここに^3.7.0以降を書くとフォーマッターの挙動が変わる

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flex_color_scheme: ^8.2.0
  nholiday_jp: ^1.0.2
  url_launcher: ^6.3.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  settings_ui: ^2.0.2
  provider: ^6.1.5
  dots_indicator: ^4.0.1
  introduction_screen: ^3.1.17
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
#  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/icon/icon_adaptive_foreground.png'
  web:
    generate: true
    image_path: 'assets/icon/icon.png'
    background_color: '#ffffff'
    theme_color: '#8E1728'

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon_transparent.png
