name: TokoBus
description: 早稲田大学所沢キャンパスのスクールバス時刻表アプリです。
publish_to: 'none'

version: 2.8.9+107

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.0
  flex_color_scheme: ^8.0.0
  nholiday_jp: ^1.0.2
  page_view_indicators: ^2.0.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  settings_ui: ^2.0.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
# flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/icon/icon_adaptive_foreground.png'
  web:
    generate: true
    image_path: 'assets/icon/icon.png'
    background_color: '#ffffff'
    theme_color: '#8E1728'

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon_transparent.png
