name: TokoBus
description: 早稲田大学所沢キャンパスのスクールバス時刻表アプリです。
publish_to: 'none'

version: 2.8.15+129

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flex_color_scheme: ^8.1.0
  nholiday_jp: ^1.0.2
  url_launcher: ^6.3.1
  http: ^1.3.0
  shared_preferences: ^2.5.2
  settings_ui: ^2.0.2
  provider: ^6.1.2
#  dots_indicator: ^2.1.2
#  introduction_screen: ^3.1.16
  dots_indicator: ^4.0.0
  introduction_screen:
    git:
      url: https://github.com/Pyozer/introduction_screen.git
      ref: 2d05d7f859442a1adff9edb00428f6cfe53fd71e

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
#  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/icon/icon_adaptive_foreground.png'
  web:
    generate: true
    image_path: 'assets/icon/icon.png'
    background_color: '#ffffff'
    theme_color: '#8E1728'

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon_transparent.png
